CREATE TABLE IF NOT EXISTS `price_review_configs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store` VARCHAR(64) NOT NULL COMMENT '店铺 ID',
  `site` VARCHAR(16) DEFAULT NULL COMMENT '站点',
  `skc_filter` VARCHAR(512) DEFAULT NULL COMMENT 'SKC 筛选',
  `start_time` VARCHAR(32) DEFAULT NULL COMMENT '开始时间',
  `end_time` VARCHAR(32) DEFAULT NULL COMMENT '结束时间',
  `agree_json` JSON DEFAULT NULL COMMENT '同意核价条件',
  `requote_json` JSON DEFAULT NULL COMMENT '重新报价条件',
  `abandon_strategy` VARCHAR(16) DEFAULT NULL COMMENT '放弃策略',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store` (`store`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='固定核价配置表';
